language: node_js
node_js:
- '11'

cache:
  directories:
  - "./node_modules"

before_script:
- npm install -g gulp-cli
- npm install

script: gulp build

# after_success:
# - curl --ftp-create-dirs -T "{404.php,footer.php,front-page.php,functions.php,header.php,index.php,page.php,style.css,static,inc}" sftp://${SFTP_USER}:${SFTP_PASSWORD}@scoutingoost1.nl/subdomains/dev/wp-content/themes/scoutingoost1
